import os
import shutil
from pathlib import Path

def cleanup():
    """
    Cleans up temporary files and directories generated by the project.
    """
    root_dir = Path(__file__).resolve().parent.parent
    print(f"Cleaning project rooted at: {root_dir}")

    # Patterns to match for deletion (glob patterns)
    patterns = [
        "**/*.pyc",
        "**/__pycache__",
        ".pytest_cache",
        ".coverage",
        "htmlcov",
        "*.log",
        "replay_log.txt",
        "captures/*",  # Content of captures
        "custom_logs/*" # Content of custom_logs
    ]

    # Explicit directories to keep but empty
    keep_dirs = ["captures", "custom_logs", "user_data"]

    for pattern in patterns:
        # Handle recursive globs manually for **
        if "**" in pattern:
            # Recursive search
            clean_pattern = pattern.replace("**/", "")
            for path in root_dir.rglob(clean_pattern):
                _remove_path(path)
        else:
            # Top level or specific paths
            # Note: rglob("*") vs glob("*") - we might want specific handling
            # If pattern is like "custom_logs/*", we handle it specifically
            if pattern.endswith("/*"):
                # Clear directory contents
                dir_path = root_dir / pattern[:-2]
                if dir_path.exists() and dir_path.is_dir():
                    print(f"Emptying directory: {dir_path.relative_to(root_dir)}")
                    for item in dir_path.iterdir():
                        if item.name == ".gitkeep":
                            continue
                        _remove_path(item)
            else:
                for path in root_dir.glob(pattern):
                    _remove_path(path)

    print("\nCleanup complete.")

def _remove_path(path):
    try:
        if path.is_file() or path.is_symlink():
            path.unlink()
            print(f"Removed file: {path.name}")
        elif path.is_dir():
            shutil.rmtree(path)
            print(f"Removed directory: {path.name}")
    except Exception as e:
        print(f"Error removing {path}: {e}")

if __name__ == "__main__":
    cleanup()
