import os
import sys
import re
import requests
import time

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO_OWNER = "IAMCANADIAN-cyber"
REPO_NAME = "ASDGPT"
API_BASE = "https://api.github.com"
PR_REVIEWS_FILE = "PR_REVIEWS.md"

def parse_pr_reviews(filepath):
    reviews = {}
    current_branch = None

    if not os.path.exists(filepath):
        print(f"Error: {filepath} not found.")
        return {}

    with open(filepath, 'r') as f:
        lines = f.readlines()

    for line in lines:
        # Match branch header: ## 1. `branch-name`
        branch_match = re.search(r"## \d+\. `(.*?)`", line)
        if branch_match:
            current_branch = branch_match.group(1)
            reviews[current_branch] = {"rec": None, "reason": None}
            continue

        if current_branch:
            # Match Rec: *   **Recommendation:** **Rec**
            rec_match = re.search(r"\*   \*\*Recommendation:\*\* \*\*(.*?)\*\*", line)
            if rec_match:
                reviews[current_branch]["rec"] = rec_match.group(1)

            # Match Reason: *   **Reasoning:** Reason
            reason_match = re.search(r"\*   \*\*Reasoning:\*\* (.*)", line)
            if reason_match:
                reviews[current_branch]["reason"] = reason_match.group(1)

    return reviews

def get_open_prs(headers):
    prs = []
    page = 1
    while True:
        url = f"{API_BASE}/repos/{REPO_OWNER}/{REPO_NAME}/pulls?state=open&per_page=100&page={page}"
        print(f"Fetching PRs page {page}...")
        resp = requests.get(url, headers=headers)
        if resp.status_code != 200:
            print(f"Error fetching PRs: {resp.status_code} {resp.text}")
            break

        data = resp.json()
        if not data:
            break

        prs.extend(data)
        page += 1

    print(f"Found {len(prs)} open PRs.")
    return prs

def post_comment(pr_number, body, headers):
    url = f"{API_BASE}/repos/{REPO_OWNER}/{REPO_NAME}/issues/{pr_number}/comments"
    data = {"body": body}
    resp = requests.post(url, headers=headers, json=data)
    if resp.status_code == 201:
        print(f"Success: Commented on PR #{pr_number}")
        return True
    else:
        print(f"Failed to comment on PR #{pr_number}: {resp.status_code} {resp.text}")
        return False

def main():
    if not GITHUB_TOKEN:
        print("Error: GITHUB_TOKEN environment variable is required.")
        sys.exit(1)

    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }

    print(f"Parsing {PR_REVIEWS_FILE}...")
    reviews = parse_pr_reviews(PR_REVIEWS_FILE)
    if not reviews:
        print("No reviews found or file is empty.")
        sys.exit(1)

    print("Fetching open PRs from GitHub...")
    prs = get_open_prs(headers)

    count = 0
    for pr in prs:
        pr_number = pr['number']
        branch_name = pr['head']['ref']

        # Check if we have a review for this branch
        # The automated tool stripped 'origin/' so it matches the ref name usually
        if branch_name in reviews:
            review = reviews[branch_name]
            rec = review.get("rec")
            reason = review.get("reason")

            if rec:
                comment_body = (
                    f"**Automated Review Advice**\n\n"
                    f"**Recommendation:** {rec}\n"
                    f"**Reasoning:** {reason}\n\n"
                    f"*(Generated by automated analysis tool)*"
                )

                print(f"Posting comment on PR #{pr_number} ({branch_name})...")
                # Uncomment to enable actual posting
                if os.environ.get("DRY_RUN") != "1":
                     post_comment(pr_number, comment_body, headers)
                     time.sleep(1) # Rate limiting
                else:
                     print(f"[DRY RUN] Would post: {comment_body}")
                count += 1
            else:
                print(f"Skipping PR #{pr_number} ({branch_name}): Incomplete review data.")
        else:
            print(f"Skipping PR #{pr_number} ({branch_name}): No review found in local file.")

    print(f"Processed {count} PRs.")

if __name__ == "__main__":
    main()
